[package]
name = "openvr-sys"
version = "0.1.0"
authors = ["Mick van Gelderen <mickvangelderen@gmail.com>"]
edition = "2018"
links = "openvr_api"

[dependencies]

[build-dependencies]
bindgen = "0.44.0"
cmake = "0.1.35"
